package models.domain;

import java.time.LocalDate;
import java.util.List;

/**
 * Domain model representing a movie.
 * <p>
 * This class encapsulates all relevant information about a movie as defined
 * in the Appendix of the Project Document. It includes metadata such as the
 * movie's title, description, release date, popularity metrics, financial
 * information, and associated entities like genres, production companies,
 * and spoken languages.
 *
 * @author all_team_during_discord_meeting
 */
public class Movie {

    /** Unique identifier of the movie. */
    private final int id;

    /** Name or title of the movie. */
    private final String name;

    /** Brief description or synopsis of the movie. */
    private final String overview;

    /** Official release date of the movie. */
    private final LocalDate releaseDate;

    /** List of genres associated with the movie. */
    private final List<Genre> genres;

    /** Official homepage URL of the movie. */
    private final String homepage;

    /** Popularity score of the movie. */
    private final double popularity;

    /** Path to the movie poster image. */
    private final String posterPath;

    /** List of production companies involved in producing the movie. */
    private final List<ProductionCompany> productionCompanies;

    /** Total revenue generated by the movie. */
    private final long revenue;

    /** Runtime of the movie in minutes. */
    private final int runtime;

    /** List of languages spoken in the movie. */
    private final List<SpokenLanguage> spokenLanguages;

    /** Current release status of the movie (e.g., Released, Post Production). */
    private final String status;

    /** Promotional tagline associated with the movie. */
    private final String tagline;

    /** Average rating score of the movie. */
    private final double voteAverage;

    /** Total number of votes received for the movie. */
    private final int voteCount;

    /**
     * Creates a new {@code Movie} instance with the specified attributes.
     *
     * @param id the unique identifier of the movie
     * @param name the name or title of the movie
     * @param overview a short description or synopsis of the movie
     * @param releaseDate the official release date of the movie
     * @param genres the list of genres associated with the movie
     * @param homepage the official homepage URL of the movie
     * @param popularity the popularity score of the movie
     * @param posterPath the path to the movie poster image
     * @param productionCompanies the list of production companies involved in the movie
     * @param revenue the total revenue generated by the movie
     * @param runtime the runtime of the movie in minutes
     * @param spokenLanguages the list of languages spoken in the movie
     * @param status the release status of the movie
     * @param tagline the promotional tagline of the movie
     * @param voteAverage the average rating score of the movie
     * @param voteCount the total number of votes received for the movie
     */
    public Movie(
            int id,
            String name,
            String overview,
            LocalDate releaseDate,
            List<Genre> genres,
            String homepage,
            double popularity,
            String posterPath,
            List<ProductionCompany> productionCompanies,
            long revenue,
            int runtime,
            List<SpokenLanguage> spokenLanguages,
            String status,
            String tagline,
            double voteAverage,
            int voteCount
    ) {
        this.id = id;
        this.name = name;
        this.overview = overview;
        this.releaseDate = releaseDate;
        this.genres = genres;
        this.homepage = homepage;
        this.popularity = popularity;
        this.posterPath = posterPath;
        this.productionCompanies = productionCompanies;
        this.revenue = revenue;
        this.runtime = runtime;
        this.spokenLanguages = spokenLanguages;
        this.status = status;
        this.tagline = tagline;
        this.voteAverage = voteAverage;
        this.voteCount = voteCount;
    }

    /**
     * Returns the unique identifier of the movie.
     *
     * @return the movie ID
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the name or title of the movie.
     *
     * @return the movie name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the overview or synopsis of the movie.
     *
     * @return the movie overview
     */
    public String getOverview() {
        return overview;
    }

    /**
     * Returns the official release date of the movie.
     *
     * @return the movie release date
     */
    public LocalDate getReleaseDate() {
        return releaseDate;
    }

    /**
     * Returns the list of genres associated with the movie.
     *
     * @return the movie genres
     */
    public List<Genre> getGenres() {
        return genres;
    }

    /**
     * Returns the official homepage URL of the movie.
     *
     * @return the homepage URL
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * Returns the popularity score of the movie.
     *
     * @return the popularity score
     */
    public double getPopularity() {
        return popularity;
    }

    /**
     * Returns the path to the movie poster image.
     *
     * @return the poster image path
     */
    public String getPosterPath() {
        return posterPath;
    }

    /**
     * Returns the list of production companies associated with the movie.
     *
     * @return the production companies
     */
    public List<ProductionCompany> getProductionCompanies() {
        return productionCompanies;
    }

    /**
     * Returns the total revenue generated by the movie.
     *
     * @return the revenue amount
     */
    public long getRevenue() {
        return revenue;
    }

    /**
     * Returns the runtime of the movie in minutes.
     *
     * @return the runtime in minutes
     */
    public int getRuntime() {
        return runtime;
    }

    /**
     * Returns the list of spoken languages in the movie.
     *
     * @return the spoken languages
     */
    public List<SpokenLanguage> getSpokenLanguages() {
        return spokenLanguages;
    }

    /**
     * Returns the release status of the movie.
     *
     * @return the movie status
     */
    public String getStatus() {
        return status;
    }

    /**
     * Returns the promotional tagline associated with the movie.
     *
     * @return the movie tagline
     */
    public String getTagline() {
        return tagline;
    }

    /**
     * Returns the average vote rating of the movie.
     *
     * @return the average vote score
     */
    public double getVoteAverage() {
        return voteAverage;
    }

    /**
     * Returns the total number of votes received for the movie.
     *
     * @return the vote count
     */
    public int getVoteCount() {
        return voteCount;
    }
}